Feature landing page
malkitbenning/teachers-pet pull request #63
Opened 2023-10-04 22:39 UTC by fowobi

create landing page using route to link it to App.js ,login button, and login form

2023-10-05 07:47 UTC, carrejoe3 requested changes
Well done, the login page looks great! I've only left a few comments

2023-10-05 07:47 UTC, carrejoe3 commented on client/src/components/LoginForm.jsx
> +
You don't need more than one line of whitespace between code blocks

2023-10-05 07:47 UTC, carrejoe3 commented on client/src/styles/login.css
> +/* body{
Do you still need this commented out code? It's good practice to not keep code as comments

2023-10-05 07:47 UTC, carrejoe3 commented on client/src/styles/login.css
Need to remove the extra whitespace in the styling blocks, just to keep things tidy

2023-10-05 07:47 UTC, carrejoe3 commented on client/src/styles/login.css
> +    height: 100vh;
```suggestion
    height: calc(100vh - 43px);
```

This will stop the scrollbar from appearing on the login page

2023-10-06 07:37 UTC, fowobi commented on client/src/components/LoginForm.jsx
> +
Thank you for the feed back, I have corrected it all.

2023-10-06 07:44 UTC, fowobi commented on client/src/styles/login.css
> +    height: 100vh;
Corrected.

2023-10-06 12:48 UTC, merged